title: Dynamiske kraftnett
author: Nils Jakob Johannesen

execute:
  execute_notebooks: force

repository:
  url: https://github.com/NilsJakob/dynamiske_kraftnett-book
  branch: master



html:
  extra_css:
    - _static/custom.css





bibtex_bibfiles:
  - references.bib

sphinx:
  config:
    bibtex_default_style: ieee
