title: Dynamiske kraftnett
author: Nils Jakob Johannesen

execute:
  execute_notebooks: false

html_theme: sphinx_book_theme

html_theme_options:
  show_prev_next: false
  secondary_sidebar_items: []

exclude_patterns:
  - 03_data/behandle_tall.ipynb